apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
  labels:
    app: nest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
        - name: nest
          imagePullPolicy: Always
          image: tienpvse/nest:4.1.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  type: LoadBalancer
  selector:
    app: nest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
